### ISSUE TITLE
Interested in getting username wpo

### ISSUE THREAD

**Issue by mancxvi** [mancxvi/wpo_i_want_your_username#1]

**Comment by mancxvi** [comment]
@wpo I'm interested in having github username wpo (it's my initials) but noticed it was taken. Would it be awful of me to ask if you could turn it over?

**Comment by WPo** [comment]
Sorry, Will, but WPo is also my initials.
Simplyfied in German: Wer zuerst kommt, malt zuerst.
Greetings - Wolfgang

**Comment by mancxvi** [comment]
Fair enough, figured I'd ask. Thank you for responding!
